name: All App Testcases Report

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate Summary Dashboard
        run: |
          node jobnow-app/generate-app-test-summary.cjs

      - name: Upload Excel Mobile Test Report
        uses: actions/upload-artifact@v4
        with:
          name: JobNow-All-App-Testcases-Report
          path: "JobNow_All_App_Testcases.xlsx"

